// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplicationPatrimoine.Data;

#nullable disable

namespace PatrimoineAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PatrimoineAPI.Models.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Banks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "BoursoBank"
                        });
                });

            modelBuilder.Entity("PatrimoineAPI.Models.SavingsAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<int>("Cap")
                        .HasColumnType("int")
                        .HasColumnName("Cap");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("InterestRate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.ToTable("SavingsAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BankId = 1,
                            Cap = 22950,
                            InterestRate = 0.024m,
                            Name = "Livret A"
                        },
                        new
                        {
                            Id = 2,
                            BankId = 1,
                            Cap = 12000,
                            InterestRate = 0.024m,
                            Name = "LDDS"
                        });
                });

            modelBuilder.Entity("PatrimoineAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "AQAAAAIAAYagAAAAEB5Dk81RPho0VpR7OuuWRvfrlEzJKOytTp3GuS5bVo7kNslNoEkDg1YLAwAnp/Thxw==",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("PatrimoineAPI.Models.UserSavingsAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("Balance");

                    b.Property<decimal>("InterestAccrued")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("InterestAccrued");

                    b.Property<int>("SavingsAccountId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SavingsAccountId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSavingsAccounts");
                });

            modelBuilder.Entity("PatrimoineAPI.Models.SavingsAccount", b =>
                {
                    b.HasOne("PatrimoineAPI.Models.Bank", "Bank")
                        .WithMany("SavingsAccounts")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("PatrimoineAPI.Models.UserSavingsAccount", b =>
                {
                    b.HasOne("PatrimoineAPI.Models.SavingsAccount", "SavingsAccount")
                        .WithMany()
                        .HasForeignKey("SavingsAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatrimoineAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SavingsAccount");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PatrimoineAPI.Models.Bank", b =>
                {
                    b.Navigation("SavingsAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
